[package]
name = "unicode-ident"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
publish = false

[dev-dependencies]
fst = "0.4"
ucd-trie = { version = "0.1", default-features = false }

[workspace]
members = ["diagram", "generate"]
